triggers:
  - name: gr1
    type: trigger
    version:
      counter: 64
      
  - name: gr2
    type: trigger
    version:
      counter: 427

  - name: gr3
    type: trigger
    version:
      counter: 0
      
  - name: gr4
    type: trigger
    version:
      counter: 0
